- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup
- name: java setup
  ansible.builtin.import_role:
   name: common
   tasks_from: java
- name: mysql setup
  ansible.builtin.import_role:
   name: common
   tasks_from: mysql-setup
- name: syatem start
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd

  