- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: python setup
  ansible.builtin.import_role:
   name: common
   tasks_from: python
- name: system setup
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd