- name: adding application user
  ansible.builtin.user: 
    name: roboshop
- name: recursively removing app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: "downloading {{component}} code to the created directory"
  ansible.builtin.get_url: 
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp
- name: "extract {{component}} application" 
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes