- name: installing maven
  ansible.builtin.dnf: 
    name: maven
    state: present
- name: installing dependancies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app
- name: renaming shipping.jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app